# TravisCI configuration for szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  # PHP 8.0
  - "nightly"

jobs:
  include:
    - name: "Lint ruleset XML file"
      php: "7.4"
      addons:
        apt:
          - "libxml2-utils"
      script:
        - "composer run-script test:xml"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer self-update --1"
  - "composer validate --strict"

install:
  - "composer update --no-interaction --verbose"

script:
  - "composer run-script test:cs"
